### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by iPolyomino** [Kasgai/kasgai#13]
https://github.com/Kasgai/kasgai/blob/3aeacd077720bf979516e5965d84f193f5c31c49/hosting/public/survey.js#L40

ここ、XSS できます。

**Comment by jyu0414** [comment]
<img width="844" alt="スクリーンショット 2019-10-24 12 42 10" src="https://user-images.githubusercontent.com/7841984/67451578-cf300b80-f65b-11e9-99bc-70e95c9a6caa.png">

修正しました．ありがとうございます
