### ISSUE TITLE
eslint の内部で脆弱性のあるコードが用いられています．

### ISSUE THREAD

**Issue by iPolyomino** [Kasgai/kasgai#6]
![Screenshot from 2019-05-30 21-26-23](https://user-images.githubusercontent.com/19319187/58632815-b8da8980-8321-11e9-81dc-0b902eb96e80.png)

**Comment by jyu0414** [comment]
これはupdateすればいいという話ですか

**Comment by iPolyomino** [comment]
そうです．

**Comment by iPolyomino** [comment]
`npm audit fix` で直る場合があります．
